### ISSUE TITLE
Error: failed to lookup Eth Txn

### ISSUE THREAD

**Issue by bajtos** [Meridian-IE/cli#5]
The first time I executed the release-rewards command today, the tool failed with the following error. When I checked the filfox explorer, I found that the transaction was added to the mempool and eventually accepted by the network.

https://filfox.info/en/message/0x5b3dca582227edf6e1553965aaadbcf705976a27ed289c6f8033cf1c2baa5b09?t=4

```
❯ npx @meridian-ie/cli release-rewards
Please sign on your ledger...
0x5b3dca582227edf6e1553965aaadbcf705976a27ed289c6f8033cf1c2baa5b09
Awaiting confirmation...
meridian release-rewards

Release rewards

Options:
  -a, --address     Contract address (or $MERIDIAN_ADDRESS)  [string] [required]
  -g, --glif-token  GLIF token (or $MERIDIAN_GLIF_TOKEN)     [string] [required]
  -v, --version     Show version number                                [boolean]
  -h, --help        Show help                                          [boolean]

Error: could not coalesce error (error={ "code": 1, "message": "failed to lookup Eth Txn 0x5b3dca582227edf6e1553965aaadbcf705976a27ed289c6f8033cf1c2baa5b09 as bafy2bzacebnt3ssyeit635xbku4wlkvnxt3qlf3ke7wsrhdpqaz46hblvjnqs: failed to load message: ipld: could not find bafy2bzacebnt3ssyeit635xbku4wlkvnxt3qlf3ke7wsrhdpqaz46hblvjnqs" }, payload={ "id": 13, "jsonrpc": "2.0", "method": "eth_getTransactionReceipt", "params": [ "0x5b3dca582227edf6e1553965aaadbcf705976a27ed289c6f8033cf1c2baa5b09" ] }, code=UNKNOWN_ERROR, version=6.13.4)
    at makeError (file:///Users/bajtos/.npm/_npx/c512964515528db2/node_modules/ethers/lib.esm/utils/errors.js:124:21)
    at JsonRpcProvider.getRpcError (file:///Users/bajtos/.npm/_npx/c512964515528db2/node_modules/ethers/lib.esm/providers/provider-jsonrpc.js:726:16)
    at file:///Users/bajtos/.npm/_npx/c512964515528db2/node_modules/ethers/lib.esm/providers/provider-jsonrpc.js:298:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'UNKNOWN_ERROR',
  error: {
    code: 1,
    message: 'failed to lookup Eth Txn 0x5b3dca582227edf6e1553965aaadbcf705976a27ed289c6f8033cf1c2baa5b09 as bafy2bzacebnt3ssyeit635xbku4wlkvnxt3qlf3ke7wsrhdpqaz46hblvjnqs: failed to load message: ipld: could not find bafy2bzacebnt3ssyeit635xbku4wlkvnxt3qlf3ke7wsrhdpqaz46hblvjnqs'
  },
  payload: {
    method: 'eth_getTransactionReceipt',
    params: [
      '0x5b3dca582227edf6e1553965aaadbcf705976a27ed289c6f8033cf1c2baa5b09'
    ],
    id: 13,
    jsonrpc: '2.0'
  },
  shortMessage: 'could not coalesce error'
}
```

**Comment by juliangruber** [comment]
I believe this is an error we can't catch directly (it's thrown by the provider). I don't know how to fix this, and think the CLI user needs to retry. I believe this is also a JSON-RPC provider issue (Glif). Please reopen if you disagree

**Comment by bajtos** [comment]
I was hoping that we can handle this error by wrapping `tx.wait()` with `pRetry`, but maybe that would not work 🤷🏻

**Comment by juliangruber** [comment]
https://github.com/Meridian-IE/cli/pull/6
